//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTiet_DonHang = new HashSet<ChiTiet_DonHang>();
        }
    
        public int id { get; set; }
        public System.DateTime ngay { get; set; }
        public int tongtien { get; set; }
        public bool dathanhtoan { get; set; }
        public bool dagiaohang { get; set; }
        public string diachi_nguoinhan { get; set; }
        public string ten_nguoinhan { get; set; }
        public string sdt_nguoinhan { get; set; }
        public string tennv { get; set; }
        public bool active { get; set; }
        public Nullable<int> nguoidung_id { get; set; }
        public Nullable<int> khachhang_id { get; set; }
    
        public virtual ICollection<ChiTiet_DonHang> ChiTiet_DonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
