//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauSac
    {
        public MauSac()
        {
            this.SanPham_Tag = new HashSet<SanPham_Tag>();
        }
    
        public int id { get; set; }
        public string giatri { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<SanPham_Tag> SanPham_Tag { get; set; }
    }
}
