//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ghsgdytyttysvdgvashvdghsd : DbContext
    {
        public ghsgdytyttysvdgvashvdghsd()
            : base("name=ghsgdytyttysvdgvashvdghsd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTiet_DonHang> ChiTiet_DonHang { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<HangSX> HangSXes { get; set; }
        public DbSet<HinhAnh> HinhAnhs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<KichThuoc> KichThuocs { get; set; }
        public DbSet<MauSac> MauSacs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<NhomSanPham> NhomSanPhams { get; set; }
        public DbSet<SanPham_Tag> SanPham_Tag { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
    }
}
