//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int id { get; set; }
        public string tendangnhap { get; set; }
        public string tendaydu { get; set; }
        public string email { get; set; }
        public string matkhau { get; set; }
        public bool active { get; set; }
        public int group_id { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
