//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomSanPham
    {
        public NhomSanPham()
        {
            this.NhomSanPhams1 = new HashSet<NhomSanPham>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<int> nhomcha_id { get; set; }
        public string mota { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<NhomSanPham> NhomSanPhams1 { get; set; }
        public virtual NhomSanPham NhomSanPham1 { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
