//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_Tag
    {
        public SanPham_Tag()
        {
            this.ChiTiet_DonHang = new HashSet<ChiTiet_DonHang>();
        }
    
        public int id { get; set; }
        public int soluong { get; set; }
        public Nullable<int> kichthuoc_id { get; set; }
        public Nullable<int> mausac_id { get; set; }
        public Nullable<int> sanpham_id { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<ChiTiet_DonHang> ChiTiet_DonHang { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
