//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.SanPham_Tag = new HashSet<SanPham_Tag>();
        }
    
        public int id { get; set; }
        public string masp { get; set; }
        public string ten { get; set; }
        public string mota { get; set; }
        public int gia { get; set; }
        public bool active { get; set; }
        public Nullable<int> hangsx_id { get; set; }
        public Nullable<int> nhomsanpham_id { get; set; }
    
        public virtual HangSX HangSX { get; set; }
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        public virtual NhomSanPham NhomSanPham { get; set; }
        public virtual ICollection<SanPham_Tag> SanPham_Tag { get; set; }
    }
}
