// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nothing2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nothing2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311231638420_nothing2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
