// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class sua_SanPhamTag_ChiTietSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sua_SanPhamTag_ChiTietSP));
        
        string IMigrationMetadata.Id
        {
            get { return "201310301518297_sua_SanPhamTag_ChiTietSP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
