// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class them_class_quyen_han : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_class_quyen_han));
        
        string IMigrationMetadata.Id
        {
            get { return "201310100935243_them_class_quyen_han"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
