// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_base));
        
        string IMigrationMetadata.Id
        {
            get { return "201311010217526_base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
