// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nothing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nothing));
        
        string IMigrationMetadata.Id
        {
            get { return "201311231600592_nothing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
