// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NhanVien_Them_ThuocTinh_group_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NhanVien_Them_ThuocTinh_group_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201309291114551_NhanVien_Them_ThuocTinh_group_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
