// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class them_forgot_password_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_forgot_password_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201310171438128_them_forgot_password_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
