// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class them_thuoc_tinh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_thuoc_tinh));
        
        string IMigrationMetadata.Id
        {
            get { return "201310090453113_them_thuoc_tinh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
