// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cap_nhat_tpic_phanhoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cap_nhat_tpic_phanhoi));
        
        string IMigrationMetadata.Id
        {
            get { return "201310031534039_cap_nhat_tpic_phanhoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
