// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class sua_tenhsx_to_ten : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sua_tenhsx_to_ten));
        
        string IMigrationMetadata.Id
        {
            get { return "201310220310293_sua_tenhsx_to_ten"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
