// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class the_quanhe_sanpham_hinhanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(the_quanhe_sanpham_hinhanh));
        
        string IMigrationMetadata.Id
        {
            get { return "201311020354200_the_quanhe_sanpham_hinhanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
