// <auto-generated />
namespace qdtest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class them_mota_cho_kichthuoc_giatri : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_mota_cho_kichthuoc_giatri));
        
        string IMigrationMetadata.Id
        {
            get { return "201310191620297_them_mota_cho_kichthuoc_giatri"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
